 <footer
                                                                        class="nk-footer
                                                                        bg-theme
                                                                        ov-h">
                                                                        <section
                                                                            class="section
                                                                            section-m
                                                                            section-footer
                                                                            tc-light
                                                                            bg-transparent
                                                                            pb-0
                                                                            ov-h">
                                                                            <div
                                                                                class="container">
                                                                                <!-- Block @s -->
                                                                                <div
                                                                                    class="nk-block
                                                                                    block-footer
                                                                                    mgb-m30">
                                                                                    <div
                                                                                        class="row
                                                                                        justify-content-between">
                                                                                        <div
                                                                                            class="col-sm-3
                                                                                            mb-sm-0
                                                                                            col-6">
                                                                                            <div
                                                                                                class="wgs
                                                                                                wgs-menu
                                                                                                animated"
                                                                                                data-animate="fadeInUp"
                                                                                                data-delay="0.1">
                                                                                                <h6
                                                                                                    class="wgs-title">Help</h6>
                                                                                                <div
                                                                                                    class="wgs-body">
                                                                                                    <ul
                                                                                                        class="wgs-links">
                                                                                                        <li><a
                                                                                                                href="learn-defi.html">Learn
                                                                                                                DeFi</a></li>
                                                                                                        <li><a
                                                                                                                href="career.html">Careers</a></li>
                                                                                                        <li><a
                                                                                                                href="https://drive.google.com/file/d/12ni8yTUiJDG8-XJKNG-4sOiOvXMPP135/view?usp=sharing">White
                                                                                                                Paper</a></li>
                                                                                                        <li><a
                                                                                                                href="contact.html">Contact</a></li>
                                                                                                    </ul>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div><!-- .col -->
                                                                                        <div
                                                                                            class="col-sm-3
                                                                                            mb-sm-0
                                                                                            col-6">
                                                                                            <div
                                                                                                class="wgs
                                                                                                wgs-menu
                                                                                                animated"
                                                                                                data-animate="fadeInUp"
                                                                                                data-delay="0.2">
                                                                                                <h6
                                                                                                    class="wgs-title">Company</h6>
                                                                                                <div
                                                                                                    class="wgs-body">
                                                                                                    <ul
                                                                                                        class="wgs-links">
                                                                                                        <li><a
                                                                                                                href="about-defi.html">About
                                                                                                                DeFi</a></li>
                                                                                                        <li><a
                                                                                                                href="investor-relations.html">Investor
                                                                                                                Relations</a></li>
                                                                                                        <li><a
                                                                                                                href="mission.html">Mission
                                                                                                                &
                                                                                                                Vission</a></li>
                                                                                                        <li><a
                                                                                                                href="partner.html">Partners</a></li>
                                                                                                    </ul>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div><!-- .col -->
                                                                                        <div
                                                                                            class="col-md-3
                                                                                            col-sm-4
                                                                                            mb-sm-0
                                                                                            col-6">
                                                                                            <div
                                                                                                class="wgs
                                                                                                wgs-menu
                                                                                                animated"
                                                                                                data-animate="fadeInUp"
                                                                                                data-delay="0.3">
                                                                                                <h6
                                                                                                    class="wgs-title">DeFi
                                                                                                    Products</h6>
                                                                                                <div
                                                                                                    class="wgs-body">
                                                                                                    <ul
                                                                                                        class="wgs-links">
                                                                                                        <li><a
                                                                                                                href="defi-asset-management.html">DeFi
                                                                                                                Asset
                                                                                                                Management</a></li>
                                                                                                        <li><a
                                                                                                                href="defi-venture.html">DeFi
                                                                                                                Venture</a></li>
                                                                                                        <li><a
                                                                                                                href="defi-governance.html">DeFi
                                                                                                                Governance</a></li>
                                                                                                        <li><a
                                                                                                                href="defi-treasury.html">DeFi
                                                                                                                Treasury</a></li>
                                                                                                    </ul>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div><!-- .col -->
                                                                                        <div
                                                                                            class="col-sm-2
                                                                                            mb-sm-0
                                                                                            col-6">
                                                                                            <div
                                                                                                class="wgs
                                                                                                wgs-menu
                                                                                                animated"
                                                                                                data-animate="fadeInUp"
                                                                                                data-delay="0.4">
                                                                                                <h6
                                                                                                    class="wgs-title">Follow</h6>
                                                                                                <div
                                                                                                    class="wgs-body">
                                                                                                    <ul
                                                                                                        class="wgs-links">
                                                                                                        <li><a
                                                                                                                href="#">Twitter</a></li>
                                                                                                        <li><a
                                                                                                                href="#">YouTube</a></li>
                                                                                                        <li><a
                                                                                                                href="#">Medium</a></li>
                                                                                                        <li><a
                                                                                                                href="#">LinkedIn</a></li>
                                                                                                    </ul>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div><!-- .col -->
                                                                                    </div><!-- .row -->
                                                                                </div><!-- .block @e -->
                                                                            </div>
                                                                        </section>
                                                                        <div
                                                                            class="section
                                                                            section-m
                                                                            footer-bottom
                                                                            animated"
                                                                            data-animate="fadeInUp"
                                                                            data-delay="0.5">
                                                                            <div
                                                                                class="container">
                                                                                <div
                                                                                    class="row
                                                                                    justify-content-md-between
                                                                                    align-items-center">
                                                                                    <div
                                                                                        class="col-lg-6
                                                                                        col-md-3
                                                                                        col-sm-4">
                                                                                        <a
                                                                                            href="index.html"
                                                                                            class="wgs-logo-s2
                                                                                            d-inline-block
                                                                                            mb-2
                                                                                            mb-md-0">
                                                                                            <img
                                                                                                src="images/logo-full-white.png"
                                                                                                srcset="images/logo-full-white2x.png
                                                                                                2x"
                                                                                                alt="logo">
                                                                                        </a>
                                                                                    </div>
                                                                                    <div
                                                                                        class="col-lg-6
                                                                                        col-md-8">
                                                                                        <div
                                                                                            class="copyright-text">
                                                                                            <ul
                                                                                                class="d-flex
                                                                                                justify-content-between
                                                                                                align-items-center
                                                                                                flex-wrap
                                                                                                flex-md-nowrap">
                                                                                                <li><a
                                                                                                        href="https://client.dexfintech.net/page/terms-and-condition">Terms
                                                                                                        of
                                                                                                        Service</a></li>
                                                                                                <li><a
                                                                                                        href="https://client.dexfintech.net/page/privacy-policy">Privacy
                                                                                                        Policy</a></li>
                                                                                                <li><p>©2022
                                                                                                        DexFintech,
                                                                                                        Inc.
                                                                                                        All
                                                                                                        Rights
                                                                                                        Reserved</p></li>
                                                                                            </ul>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div
                                                                            class="nk-ovm
                                                                            shape-z7
                                                                            ov-h"></div>
                                                                    </footer>
                                                                </div>


                                                                <!-- preloader -->
                                                                <div
                                                                    class="preloader
                                                                    preloader-alt
                                                                    no-split"><span
                                                                        class="spinner
                                                                        spinner-alt"><img
                                                                            class="spinner-brand"
                                                                            src="images/logo-full-white.png"
                                                                            alt=""></span></div>
                                                                <!-- JavaScript -->
                                                                <script
                                                                    src="assets/js/jquery.bundle1bce.js?ver=1930"></script>
                                                                <script
                                                                    src="assets/js/scripts1bce.js?ver=1930"></script>
                                                                <script
                                                                    src="assets/js/charts0c67.js?var=161"></script>
                                                                   <script src="//code.tidio.co/mninnizgeedggffezm4cwywdmiw9uq8g.js" async></script>
                                                            </body>
                      
                                                            <!-- Mirrored from dexfintech.net/about-defi.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 22 Jan 2023 19:04:09 GMT -->
                                                        </html>